# -*- coding: utf-8 -*-
"""question-0001-usecase-generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17aQwGeqsXsOApsIUwl4YUlRY-SaKcq52

**Funcion caso de Uso Pregunta 1**
"""

import random
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler

def generar_caso_de_uso_analizar_estado_bomba():
    """
    Genera datos aleatorios y calcula el resultado esperado

    Salidas:
        df_entrenamiento (pd.DataFrame): Datos para entrenar el modelo.
        datos_nuevos (list): Datos a evaluar.
        resultado_esperado (dict): Respuesta correcta calculada internamente.
    """
    # 1. GENERACIÓN DE DATOS SINTÉTICOS (Entrenamiento)
    num_filas = random.randint(80, 150)
    data = {
        'flujo_m3h': [random.uniform(50, 150) for _ in range(num_filas)],
        'presion_bar': [random.uniform(1.0, 5.5) for _ in range(num_filas)],
        'temp_c': [random.uniform(15, 65) for _ in range(num_filas)]
    }

    # Lógica física para determinar el estado real (Cavitación: Baja presión + Alta Temp)
    data['estado'] = [1 if (p < 2.0 and t > 45) else 0
                      for p, t in zip(data['presion_bar'], data['temp_c'])]

    # Cálculo de potencia (relacionada con flujo y presión)
    data['potencia_kw'] = [(f * p / 25) + random.uniform(1, 4)
                           for f, p in zip(data['flujo_m3h'], data['presion_bar'])]

    df_entrenamiento = pd.DataFrame(data)

    # 2. GENERACIÓN DEL CASO DE PRUEBA (Input)
    datos_nuevos = [
        random.uniform(50, 150), # flujo
        random.uniform(1.0, 5.5), # presion
        random.uniform(15, 65),  # temp
        random.uniform(10, 35)   # potencia
    ]

    # 3. CÁLCULO INTERNO DEL RESULTADO (Output esperado)
    # Se entrena un modelo local para asegurar que el generador sea autónomo
    X = df_entrenamiento[['flujo_m3h', 'presion_bar', 'temp_c', 'potencia_kw']]
    y = df_entrenamiento['estado']

    sc = StandardScaler()
    X_scaled = sc.fit_transform(X)

    clf = RandomForestClassifier(n_estimators=100, random_state=42)
    clf.fit(X_scaled, y)

    # Predecir sobre el caso de prueba
    input_scaled = sc.transform(np.array(datos_nuevos).reshape(1, -1))
    pred = clf.predict(input_scaled)[0]
    prob = clf.predict_proba(input_scaled)[0][1]

    txt_resultado = "Crítico (Riesgo de Cavitación)" if pred == 1 else "Operativo (Normal)"

    resultado_esperado = {
        "estado_predicho": txt_resultado,
        "probabilidad_critica": f"{prob * 100:.2f}%"
    }

    return df_entrenamiento, datos_nuevos, resultado_esperado

# --- EJEMPLO DE USO ---

df_entrenar, caso_test, output_esperado = generar_caso_de_uso_analizar_estado_bomba()

print("🚀 --- CASO DE USO GENERADO --- 🚀")
print(f"📊 Filas de entrenamiento: {len(df_entrenar)}")
print(f"📥 Input (Datos nuevos): {caso_test}")
print(f"📤 Output esperado (Estado): {output_esperado['estado_predicho']}")
print(f"📤 Output esperado (Probabilidad): {output_esperado['probabilidad_critica']}")