# -*- coding: utf-8 -*-
"""question-0003-usecase-generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GSZKPX0hsXx2aLEgIOCLAi4DXUWOBAJZ

**Funcion de Casos de Uso problema 3**
"""

import random
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

def generar_caso_de_uso_clasificar_diagnostico_maquina():
    """
    Genera datos aleatorios y calcula el resultado esperado de forma
    autónoma

    Salidas:
        df_historico (pd.DataFrame): Datos de entrenamiento (vibraciones y temp).
        lectura_actual (list): Caso de prueba para evaluar.
        resultado_esperado (dict): Diagnóstico y confianza calculados internamente.
    """
    # 1. GENERACIÓN DE DATOS SINTÉTICOS (Entrenamiento)
    num_filas = random.randint(100, 150)
    data = {'vib_x': [], 'vib_y': [], 'vib_z': [], 'temp_rodamientos': [], 'diagnostico': []}

    for _ in range(num_filas):
        # 0: Normal, 1: Desalineación (vibración en X), 2: Desbalanceo (vibración en Y)
        tipo = random.choice([0, 1, 2])

        if tipo == 0: # Estado Normal
            vx, vy, vz = random.uniform(0.1, 0.8), random.uniform(0.1, 0.8), random.uniform(0.1, 0.4)
            t = random.uniform(30, 38)
        elif tipo == 1: # Desalineación
            vx, vy, vz = random.uniform(2.5, 5.0), random.uniform(0.5, 1.5), random.uniform(0.1, 0.6)
            t = random.uniform(40, 55)
        else: # Desbalanceo
            vx, vy, vz = random.uniform(0.5, 1.5), random.uniform(2.5, 5.0), random.uniform(0.1, 0.6)
            t = random.uniform(35, 45)

        data['vib_x'].append(vx)
        data['vib_y'].append(vy)
        data['vib_z'].append(vz)
        data['temp_rodamientos'].append(t)
        data['diagnostico'].append(tipo)

    df_historico = pd.DataFrame(data)

    # 2. GENERACIÓN DEL REGISTRO DE PRUEBA (Input)
    # Generamos un caso aleatorio que podría caer en cualquier categoría
    lectura_actual = [
        random.uniform(0.1, 5.0), # vib_x
        random.uniform(0.1, 5.0), # vib_y
        random.uniform(0.1, 0.8), # vib_z
        random.uniform(30, 55)    # temp
    ]

    # 3. CÁLCULO INTERNO DEL OUTPUT (Independiente)
    X = df_historico[['vib_x', 'vib_y', 'vib_z', 'temp_rodamientos']]
    y = df_historico['diagnostico']

    sc = StandardScaler()
    X_scaled = sc.fit_transform(X)

    # Modelo interno para generar el resultado esperado
    knn_interno = KNeighborsClassifier(n_neighbors=5)
    knn_interno.fit(X_scaled, y)

    # Procesar la lectura de prueba
    input_array = np.array(lectura_actual).reshape(1, -1)
    input_scaled = sc.transform(input_array)
    pred_codificada = knn_interno.predict(input_scaled)[0]
    probabilidades = knn_interno.predict_proba(input_scaled)[0]

    mapeo = {0: "Normal", 1: "Desalineación", 2: "Desbalanceo"}

    resultado_esperado = {
        "diagnostico_detectado": mapeo[pred_codificada],
        "confianza": f"{np.max(probabilidades) * 100:.2f}%"
    }

    return df_historico, lectura_actual, resultado_esperado

# --- PRUEBA EN UN ENTORNO LIMPIO ---

# Llamada a la función (desempaquetando los 3 elementos)
df_hist, caso_test, output_test = generar_caso_de_uso_clasificar_diagnostico_maquina()

print("✅ Generador de Diagnóstico de Máquinas ejecutado con éxito")
print(f"📥 Lectura de Sensores (Input): {caso_test}")
print(f"📤 Resultado Esperado (Output): {output_test}")