# -*- coding: utf-8 -*-
"""question-0004-usecase-generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SIX8i2AgoIfs03lTtSvxZXxkXSIxVAPj

**Funcion de Casos de Uso problema 3**
"""

import random
import pandas as pd
import numpy as np
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error

def generar_caso_de_uso_estimar_eficiencia_termica():
    """
    Genera datos aleatorios y calcula el resultado esperado de forma
    autónoma

    Salidas:
        df_historico (pd.DataFrame): Datos de entrenamiento del intercambiador.
        condiciones_nuevas (list): Caso de prueba (flujo, temp, viscosidad, ensuciamiento).
        resultado_esperado (dict): Respuesta correcta calculada internamente.
    """
    # 1. GENERACIÓN DE DATOS SINTÉTICOS (Entrenamiento)
    num_filas = random.randint(100, 150)

    flujos = [random.uniform(1.0, 6.0) for _ in range(num_filas)]
    deltas = [random.uniform(20, 80) for _ in range(num_filas)]
    viscos = [random.uniform(0.8, 1.8) for _ in range(num_filas)]
    ensuc = [random.uniform(0.001, 0.05) for _ in range(num_filas)]

    # Lógica térmica: La eficiencia baja si aumenta el ensuciamiento y el flujo masivo
    # (simplificación del método NTU-Eficiencia)
    eficiencias = [
        92 - (f * 1.8) - (e * 350) - (v * 1.2) + random.uniform(-1.5, 1.5)
        for f, e, v in zip(flujos, ensuc, viscos)
    ]

    df_historico = pd.DataFrame({
        'flujo_kg_s': flujos,
        'delta_t_entrada': deltas,
        'viscosidad_cp': viscos,
        'indice_ensuciamiento': ensuc,
        'eficiencia_real': eficiencias
    })

    # 2. GENERACIÓN DEL REGISTRO DE PRUEBA (Input)
    condiciones_nuevas = [
        random.uniform(1.0, 6.0),    # flujo_kg_s
        random.uniform(20, 80),     # delta_t_entrada
        random.uniform(0.8, 1.8),    # viscosidad_cp
        random.uniform(0.001, 0.05)  # indice_ensuciamiento
    ]

    # 3. CÁLCULO INTERNO DEL OUTPUT (Independiente)
    X = df_historico[['flujo_kg_s', 'delta_t_entrada', 'viscosidad_cp', 'indice_ensuciamiento']]
    y = df_historico['eficiencia_real']

    # Escalador y modelo interno para generar la "verdad" del test
    scaler_int = StandardScaler()
    X_s = scaler_int.fit_transform(X)

    model_int = Ridge(alpha=1.0)
    model_int.fit(X_s, y)

    # Calcular MAE interno
    y_pred_train = model_int.predict(X_s)
    mae_int = mean_absolute_error(y, y_pred_train)

    # Predicción para el caso de uso
    input_array = np.array(condiciones_nuevas).reshape(1, -1)
    input_scaled = scaler_int.transform(input_array)
    pred_int = model_int.predict(input_scaled)[0]

    # Limitar el resultado a valores físicos coherentes (0-100%)
    pred_final = max(0, min(100, pred_int))

    resultado_esperado = {
        "eficiencia_estimada_porcentaje": round(float(pred_final), 2),
        "error_medio_modelo": round(float(mae_int), 3)
    }

    return df_historico, condiciones_nuevas, resultado_esperado

# --- PRUEBA EN UN ENTORNO LIMPIO ---

# Llamada a la función (retorna los 2 argumentos y el resultado esperado)
df_termico, input_test, output_test = generar_caso_de_uso_estimar_eficiencia_termica()

print("✅ Generador de Eficiencia Térmica finalizado")
print(f"📥 Condiciones de entrada (Sensores): {input_test}")
print(f"📤 Respuesta esperada (Diccionario): {output_test}")