# -*- coding: utf-8 -*-
"""question-0001-usecase-generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZIpPKK0lMAfFVmbn65k9gkSY1u20AnyC

**Funcion caso de Uso Pregunta 1**
"""

import random
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler

def generar_caso_de_uso_analizar_estado_bomba():
    """
    Genera datos aleatorios y calcula el resultado esperado de forma
    autónoma, cumpliendo con el formato de dos salidas (input/output).

    Salidas:
        input_data (dict): Diccionario con las claves 'df_entrenamiento' y 'datos_nuevos'.
        output_data (dict): Resultado esperado de la predicción.
    """
    # 1. GENERACIÓN DE DATOS SINTÉTICOS (Entrenamiento)
    num_filas = random.randint(80, 150)
    data = {
        'flujo_m3h': [random.uniform(50, 150) for _ in range(num_filas)],
        'presion_bar': [random.uniform(1.0, 5.5) for _ in range(num_filas)],
        'temp_c': [random.uniform(15, 65) for _ in range(num_filas)]
    }

    # Lógica física: Cavitación si baja presión y alta temperatura
    data['estado'] = [1 if (p < 2.0 and t > 45) else 0
                      for p, t in zip(data['presion_bar'], data['temp_c'])]

    # Potencia relacionada con flujo y presión
    data['potencia_kw'] = [(f * p / 25) + random.uniform(1, 4)
                           for f, p in zip(data['flujo_m3h'], data['presion_bar'])]

    df_entrenamiento = pd.DataFrame(data)

    # 2. GENERACIÓN DEL REGISTRO DE PRUEBA (Datos nuevos)
    datos_nuevos = [
        random.uniform(50, 150), # flujo
        random.uniform(1.0, 5.5), # presion
        random.uniform(15, 65),  # temp
        random.uniform(10, 35)   # potencia
    ]

    # 3. CÁLCULO INTERNO DEL RESULTADO (Independiente)
    X = df_entrenamiento[['flujo_m3h', 'presion_bar', 'temp_c', 'potencia_kw']]
    y = df_entrenamiento['estado']

    sc = StandardScaler()
    X_scaled = sc.fit_transform(X)

    clf = RandomForestClassifier(n_estimators=100, random_state=42)
    clf.fit(X_scaled, y)

    # Predecir sobre el caso de prueba (usando DataFrame para evitar el Warning de nombres de columnas)
    X_test_df = pd.DataFrame([datos_nuevos], columns=X.columns)
    input_scaled = sc.transform(X_test_df)

    pred = clf.predict(input_scaled)[0]
    prob = clf.predict_proba(input_scaled)[0][1]

    txt_resultado = "Crítico (Riesgo de Cavitación)" if pred == 1 else "Operativo (Normal)"

    # 4. ESTRUCTURAR SALIDAS SEGÚN REQUERIMIENTO
    input_data = {
        "df_entrenamiento": df_entrenamiento,
        "datos_nuevos": datos_nuevos
    }

    output_data = {
        "estado_predicho": txt_resultado,
        "probabilidad_critica": f"{prob * 100:.2f}%"
    }

    return input_data, output_data

# --- EJEMPLO DE USO PARA VALIDACIÓN ---
caso_input, caso_output = generar_caso_de_uso_analizar_estado_bomba()
print(f"Input keys: {caso_input.keys()}")
print(f"Output esperado: {caso_output}")