# -*- coding: utf-8 -*-
"""question-0004-usecase-generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1buj-1dO-Ze_NCovFoxmdCVoefMDiJBc_

**Funcion caso de Uso Pregunta 4**
"""

import random
import pandas as pd
import numpy as np
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error

def generar_caso_de_uso_estimar_eficiencia_termica():
    """
    Genera datos aleatorios y calcula el resultado esperado de forma
    autónoma, cumpliendo con el formato de dos salidas (input/output).

    Salidas:
        input_data (dict): Diccionario con las claves 'df_historico' y 'condiciones_nuevas'.
        output_data (dict): Resultado esperado de la predicción térmica.
    """
    # 1. GENERACIÓN DE DATOS SINTÉTICOS (Entrenamiento)
    num_filas = random.randint(110, 160)

    flujos = [random.uniform(1.0, 6.0) for _ in range(num_filas)]
    deltas = [random.uniform(20, 80) for _ in range(num_filas)]
    viscos = [random.uniform(0.8, 1.8) for _ in range(num_filas)]
    ensuc = [random.uniform(0.001, 0.05) for _ in range(num_filas)]

    # Lógica térmica: La eficiencia baja si aumenta el ensuciamiento y el flujo
    eficiencias = [
        92 - (f * 1.8) - (e * 350) - (v * 1.2) + random.uniform(-1.5, 1.5)
        for f, e, v in zip(flujos, ensuc, viscos)
    ]

    df_historico = pd.DataFrame({
        'flujo_kg_s': flujos,
        'delta_t_entrada': deltas,
        'viscosidad_cp': viscos,
        'indice_ensuciamiento': ensuc,
        'eficiencia_real': eficiencias
    })

    # 2. GENERACIÓN DEL REGISTRO DE PRUEBA (Input)
    condiciones_nuevas = [
        random.uniform(1.0, 6.0),    # flujo_kg_s
        random.uniform(20, 80),      # delta_t_entrada
        random.uniform(0.8, 1.8),    # viscosidad_cp
        random.uniform(0.001, 0.05)   # indice_ensuciamiento
    ]

    # 3. CÁLCULO INTERNO DEL RESULTADO (Independiente)
    X = df_historico[['flujo_kg_s', 'delta_t_entrada', 'viscosidad_cp', 'indice_ensuciamiento']]
    y = df_historico['eficiencia_real']

    scaler_int = StandardScaler()
    X_scaled = scaler_int.fit_transform(X)

    model_int = Ridge(alpha=1.0)
    model_int.fit(X_scaled, y)

    # Calcular MAE interno
    mae_int = mean_absolute_error(y, model_int.predict(X_scaled))

    # Predicción para el caso de uso (usando DataFrame para evitar Warnings)
    input_df = pd.DataFrame([condiciones_nuevas], columns=X.columns)
    input_scaled = scaler_int.transform(input_df)
    pred_int = model_int.predict(input_scaled)[0]

    # Limitar resultado a valores físicos (0-100%)
    pred_final = max(0, min(100, pred_int))

    # 4. ESTRUCTURAR SALIDAS SEGÚN REQUERIMIENTO
    input_data = {
        "df_historico": df_historico,
        "condiciones_nuevas": condiciones_nuevas
    }

    output_data = {
        "eficiencia_estimada_porcentaje": round(float(pred_final), 2),
        "error_medio_modelo": round(float(mae_int), 3)
    }

    return input_data, output_data

# --- EJEMPLO DE PRUEBA COMPLETO ---
inp, out = generar_caso_de_uso_estimar_eficiencia_termica()
print(f"Eficiencia esperada: {out['eficiencia_estimada_porcentaje']}% (Error del Modelo MAE: {out['error_medio_modelo']})")