# -*- coding: utf-8 -*-
"""question-0002-usecase-generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a2-RsTe6J-Cjd_02sLzDmER1QqCrj4A2

**Funcion caso de Uso Pregunta 2**
"""

import random
import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.preprocessing import StandardScaler

def generar_caso_de_uso_predecir_resistencia_material():
    """
    Genera datos aleatorios y calcula el resultado esperado de forma
    autónoma, cumpliendo con el formato de dos salidas (input/output).

    Salidas:
        input_data (dict): Diccionario con las claves 'df_historico' y 'configuracion_nueva'.
        output_data (dict): Resultado esperado de la predicción.
    """
    # 1. GENERACIÓN DE DATOS SINTÉTICOS (Entrenamiento)
    num_filas = random.randint(100, 150)

    # Composición: Al (balance), Mg (5-15%), Zn (2-8%), Temp (150-250°C)
    mg = [random.uniform(5, 15) for _ in range(num_filas)]
    zn = [random.uniform(2, 8) for _ in range(num_filas)]
    temp = [random.uniform(150, 250) for _ in range(num_filas)]
    al = [100 - m - z for m, z in zip(mg, zn)]

    # Lógica física: Resistencia influenciada por aleantes y temperatura
    resistencia = [
        200 + (m * 12) + (z * 15) + (t * 0.4) + random.uniform(-5, 5)
        for m, z, t in zip(mg, zn, temp)
    ]

    df_historico = pd.DataFrame({
        'Al_porcentaje': al,
        'Mg_porcentaje': mg,
        'Zn_porcentaje': zn,
        'Temp_Tratamiento': temp,
        'Limite_Elastico_MPa': resistencia
    })

    # 2. GENERACIÓN DEL CASO DE PRUEBA (Input)
    configuracion_nueva = [
        random.uniform(80, 85),  # % Al
        random.uniform(8, 12),   # % Mg
        random.uniform(3, 6),    # % Zn
        random.uniform(170, 210) # Temp
    ]

    # 3. CÁLCULO INTERNO DEL RESULTADO (Independiente)
    X = df_historico[['Al_porcentaje', 'Mg_porcentaje', 'Zn_porcentaje', 'Temp_Tratamiento']]
    y = df_historico['Limite_Elastico_MPa']

    sc = StandardScaler()
    X_scaled = sc.fit_transform(X)

    reg_interno = GradientBoostingRegressor(n_estimators=100, random_state=42)
    reg_interno.fit(X_scaled, y)

    # Predecir usando DataFrame para evitar Warnings de nombres de columnas
    input_df = pd.DataFrame([configuracion_nueva], columns=X.columns)
    input_scaled = sc.transform(input_df)
    pred_interna = reg_interno.predict(input_scaled)[0]

    # 4. ESTRUCTURAR SALIDAS SEGÚN REQUERIMIENTO
    input_data = {
        "df_historico": df_historico,
        "configuracion_nueva": configuracion_nueva
    }

    output_data = {
        "resistencia_predicha_mpa": round(float(pred_interna), 2)
    }

    return input_data, output_data

# --- EJEMPLO DE CONEXIÓN CON LA FUNCIÓN SOLUCIÓN ---
input_dict, output_esperado = generar_caso_de_uso_predecir_resistencia_material()

print(f"Input keys: {input_dict.keys()}")
print(f"Output esperado: {output_esperado}")