# -*- coding: utf-8 -*-
"""question-0002-usecase-generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19GCTF-H9jKKgPK5k0tGEUTxYItrxALNE

**Funcion de Casos de Uso problema 2**
"""

import random
import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.preprocessing import StandardScaler

def generar_caso_de_uso_predecir_resistencia_material():
    """
    Genera datos aleatorios y calcula el resultado esperado de forma
    autónoma

    Salidas:
        df_historico (pd.DataFrame): Datos para entrenar.
        configuracion_nueva (list): Caso de prueba.
        resultado_esperado (dict): Respuesta correcta calculada internamente.
    """
    # 1. GENERACIÓN DE DATOS SINTÉTICOS
    num_filas = random.randint(100, 150)

    # Composición: Al (balance), Mg (5-15%), Zn (2-8%), Temp (150-250°C)
    mg = [random.uniform(5, 15) for _ in range(num_filas)]
    zn = [random.uniform(2, 8) for _ in range(num_filas)]
    temp = [random.uniform(150, 250) for _ in range(num_filas)]
    al = [100 - m - z for m, z in zip(mg, zn)] # El resto es Aluminio

    # Lógica física para el Límite Elástico (MPa)
    # Resistencia = Base + Efecto_Mg + Efecto_Zn + Efecto_Temp + Ruido
    limite_elastico = [
        200 + (m * 12) + (z * 15) + (t * 0.4) + random.uniform(-5, 5)
        for m, z, t in zip(mg, zn, temp)
    ]

    df_historico = pd.DataFrame({
        'Al_porcentaje': al,
        'Mg_porcentaje': mg,
        'Zn_porcentaje': zn,
        'Temp_Tratamiento': temp,
        'Limite_Elastico_MPa': limite_elastico
    })

    # 2. GENERACIÓN DEL REGISTRO DE PRUEBA (Input)
    config_nueva = [
        random.uniform(80, 85), # % Al
        random.uniform(8, 12),  # % Mg
        random.uniform(3, 6),   # % Zn
        random.uniform(170, 210) # Temp
    ]

    # 3. CÁLCULO INTERNO DEL OUTPUT
    # Entrenamos un modelo local exclusivo para este caso de uso
    X = df_historico[['Al_porcentaje', 'Mg_porcentaje', 'Zn_porcentaje', 'Temp_Tratamiento']]
    y = df_historico['Limite_Elastico_MPa']

    sc = StandardScaler()
    X_scaled = sc.fit_transform(X)

    # Usamos un regresor interno para generar la "verdad" del caso de prueba
    reg_interno = GradientBoostingRegressor(n_estimators=100, random_state=42)
    reg_interno.fit(X_scaled, y)

    # Predecir el valor para el input generado
    input_array = np.array(config_nueva).reshape(1, -1)
    input_scaled = sc.transform(input_array)
    pred_interna = reg_interno.predict(input_scaled)[0]

    resultado_esperado = {
        "resistencia_predicha_mpa": round(float(pred_interna), 2)
    }

    return df_historico, config_nueva, resultado_esperado

# --- PRUEBA EN UN ENTORNO LIMPIO ---

# Llamada a la función (no requiere nada más definido)
df_lab, aleacion_test, output_test = generar_caso_de_uso_predecir_resistencia_material()

print("✅ Generador ejecutado con éxito de forma independiente")
print(f"📊 Filas generadas para entrenamiento: {len(df_lab)}")
print(f"📥 Caso de uso (Input): {aleacion_test}")
print(f"📤 Resultado Esperado (Output): {output_test}")