# -*- coding: utf-8 -*-
"""answer-0418.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jKKbvvK0bVvA63f8LrQGPwspM5QbdvFj
"""

import numpy as np
import pandas as pd


def rankear_clientes_ventana_movil(
    df: pd.DataFrame,
    cliente_col: str,
    fecha_col: str,
    monto_col: str,
    ventana: int
) -> pd.DataFrame:
    trabajo = df.copy()
    trabajo[fecha_col] = pd.to_datetime(trabajo[fecha_col], errors="coerce")
    trabajo = trabajo.dropna(subset=[cliente_col, fecha_col, monto_col])

    if trabajo.empty:
        return pd.DataFrame(columns=[fecha_col, cliente_col, "suma_movil"])

    agregado = (
        trabajo
        .groupby([cliente_col, fecha_col], as_index=False)[monto_col]
        .sum()
        .sort_values([cliente_col, fecha_col])
        .reset_index(drop=True)
    )

    agregado["suma_movil"] = agregado.groupby(cliente_col)[monto_col].transform(
        lambda s: s.rolling(window=ventana, min_periods=1).sum()
    )

    ranking = agregado.sort_values(
        [fecha_col, "suma_movil", cliente_col],
        ascending=[True, False, True],
    )

    top_por_fecha = (
        ranking
        .groupby(fecha_col, as_index=False)
        .first()[[fecha_col, cliente_col, "suma_movil"]]
        .sort_values(fecha_col)
        .reset_index(drop=True)
    )

    top_por_fecha["suma_movil"] = top_por_fecha["suma_movil"].astype(float)
    return top_por_fecha