# -*- coding: utf-8 -*-
"""answer-364.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lNy0VLZW8QTstAKHSDoPBfaXVACNIRp6
"""

# ══════════════════════════════════════════════════════════════════════════════
# aplicar_label_encoding.py
# Codificación de variables categóricas con LabelEncoder de sklearn
# ══════════════════════════════════════════════════════════════════════════════

import pandas as pd
import numpy as np
import random
from sklearn.preprocessing import LabelEncoder


# ── FUNCIÓN SOLUCIONADORA ────────────────────────────────────────────────────

def aplicar_label_encoding(
    df: pd.DataFrame,
    columna: str
) -> pd.DataFrame:
    """
    Aplica LabelEncoder a una columna categórica de un DataFrame.

    Parámetros
    ----------
    df      : DataFrame de pandas que contiene la columna a codificar.
    columna : Nombre de la columna con valores de texto (categorías).

    Retorna
    -------
    pd.DataFrame — copia del DataFrame con la columna reemplazada
                   por sus etiquetas numéricas (enteros desde 0,
                   asignados en orden alfabético de las categorías).
    """
    df_resultado = df.copy()              # no modificar el DataFrame original

    encoder = LabelEncoder()
    df_resultado[columna] = encoder.fit_transform(df_resultado[columna])

    return df_resultado


# ── GENERADOR DE CASOS DE USO ────────────────────────────────────────────────

def generar_caso_de_uso_aplicar_label_encoding():
    """
    Genera un par (input, output esperado) aleatorio para probar
    la función aplicar_label_encoding.
    """
    n  = random.randint(5, 15)
    df = pd.DataFrame({
        'categoria': np.random.choice(
            ['rojo', 'azul', 'verde', 'amarillo'], size=n
        )
    })

    input_data = {'df': df.copy(), 'columna': 'categoria'}

    df_out = df.copy()
    encoder = LabelEncoder()
    df_out['categoria'] = encoder.fit_transform(df_out['categoria'])

    return input_data, df_out


# ── PRUEBAS ──────────────────────────────────────────────────────────────────

if __name__ == "__main__":

    # ── Test 1: caso de uso aleatorio con comparación lado a lado ────────────
    print("\n" + "═" * 55)
    print("  TEST 1 — CASO DE USO ALEATORIO")
    print("═" * 55)

    caso_input, caso_output = generar_caso_de_uso_aplicar_label_encoding()
    resultado = aplicar_label_encoding(**caso_input)

    comparacion = caso_input['df'].copy()
    comparacion.columns = ['original']
    comparacion['esperado'] = caso_output['categoria'].values
    comparacion['obtenido'] = resultado['categoria'].values
    comparacion['coincide'] = comparacion['esperado'] == comparacion['obtenido']

    print(comparacion.to_string(index=True))
    print("─" * 55)
    todo_ok = comparacion['coincide'].all()
    print(f"  ✓ Todos los valores coinciden: {todo_ok}")
    print("═" * 55)

print(resultado)