# -*- coding: utf-8 -*-
"""answer-0309.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SDSs8RF8Ig3IUho4dpscXUn7zThwDwKo
"""

# evaluar_modelo_por_grupos.py
# Clasificación con GroupKFold — evita data leakage por grupos
# ══════════════════════════════════════════════════════════════════════════════

import numpy as np
import pandas as pd
from sklearn.model_selection import GroupKFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


# ── FUNCIÓN SOLUCIONADORA ────────────────────────────────────────────────────

def evaluar_modelo_por_grupos(
    df: pd.DataFrame,
    group_col: str,
    target_col: str,
    n_splits: int = 4
) -> dict:
    """
    Evalúa un clasificador binario (LogisticRegression) usando GroupKFold,
    garantizando que ningún grupo quede repartido entre train y validación.

    Parámetros
    ----------
    df         : DataFrame con columnas de grupo, target y features numéricas.
    group_col  : Nombre de la columna que identifica los grupos.
    target_col : Nombre de la columna objetivo binaria (0/1).
    n_splits   : Número de folds para GroupKFold (default 4).

    Retorna
    -------
    dict con:
        "accuracy_promedio"  : float   — promedio de accuracy sobre los folds
        "accuracy_por_fold"  : ndarray — accuracy de cada fold
        "n_grupos"           : int     — grupos únicos en group_col
    """
    # 1. Separar features, target y grupos
    X      = (df
              .drop(columns=[group_col, target_col])
              .select_dtypes(include=[np.number]))   # solo columnas numéricas
    y      = df[target_col].to_numpy()
    groups = df[group_col].to_numpy()

    # 2. Validación cruzada por grupos
    gkf        = GroupKFold(n_splits=n_splits)
    accuracies = []

    for train_idx, val_idx in gkf.split(X, y, groups=groups):
        X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_train, y_val = y[train_idx],      y[val_idx]

        # 3. Entrenar
        model = LogisticRegression(max_iter=1000)
        model.fit(X_train, y_train)

        # 4. Predecir y calcular accuracy
        y_pred = model.predict(X_val)
        acc    = accuracy_score(y_val, y_pred)
        accuracies.append(float(acc))

    accuracies = np.array(accuracies, dtype=float)

    # 5. Retornar resultados
    return {
        "accuracy_promedio": float(np.mean(accuracies)),
        "accuracy_por_fold": accuracies,
        "n_grupos"         : int(df[group_col].nunique()),
    }


# ── GENERADOR DE CASOS DE USO ────────────────────────────────────────────────

def generar_caso_de_uso_evaluar_modelo_por_grupos():
    rng = np.random.default_rng()

    n_groups    = int(rng.integers(8, 13))
    group_sizes = rng.integers(6, 13, size=n_groups)

    rows          = []
    group_effects = rng.normal(0, 0.8, size=n_groups)

    for g, size in enumerate(group_sizes):
        for _ in range(int(size)):
            x1 = rng.normal(0, 1)
            x2 = rng.normal(1, 1.2)
            x3 = rng.uniform(-2, 2)

            logit = 1.1 * x1 - 0.7 * x2 + 0.5 * x3 + group_effects[g]
            prob  = 1 / (1 + np.exp(-logit))
            y_val = rng.binomial(1, prob)

            rows.append({
                "grupo"  : f"G{g+1:02d}",
                "x1"     : x1,
                "x2"     : x2,
                "x3"     : x3,
                "target" : y_val
            })

    df = pd.DataFrame(rows)

    if df["target"].nunique() < 2:
        half = len(df) // 2
        df.loc[:half, "target"] = 0
        df.loc[half:, "target"] = 1

    n_splits = int(rng.integers(3, min(6, n_groups + 1)))

    input_data = {
        "df"        : df.copy(),
        "group_col" : "grupo",
        "target_col": "target",
        "n_splits"  : n_splits,
    }

    # Calcular output esperado
    X      = df.drop(columns=["grupo", "target"]).select_dtypes(include=[np.number])
    y_arr  = df["target"].to_numpy()
    groups = df["grupo"].to_numpy()
    gkf    = GroupKFold(n_splits=n_splits)
    accs   = []

    for tr_idx, vl_idx in gkf.split(X, y_arr, groups=groups):
        m = LogisticRegression(max_iter=1000)
        m.fit(X.iloc[tr_idx], y_arr[tr_idx])
        accs.append(float(accuracy_score(y_arr[vl_idx], m.predict(X.iloc[vl_idx]))))

    accs = np.array(accs, dtype=float)

    output_data = {
        "accuracy_promedio": float(np.mean(accs)),
        "accuracy_por_fold": accs,
        "n_grupos"         : int(df["grupo"].nunique()),
    }

    return input_data, output_data


# ── PRUEBA AUTOMÁTICA ─────────────────────────────────────────────────────────

if __name__ == "__main__":

    # --- Test 1: caso de uso aleatorio ---
    caso_input, caso_output = generar_caso_de_uso_evaluar_modelo_por_grupos()
    resultado = evaluar_modelo_por_grupos(**caso_input)


    print("═" * 55)
    print("  RESULTADO OBTENIDO vs RESULTADO ESPERADO")
    print("═" * 55)
    print(f"  n_grupos          : {resultado['n_grupos']}  (esperado: {caso_output['n_grupos']})")
    print(f"  n_splits usados   : {caso_input['n_splits']}")
    print(f"  accuracy_promedio : {resultado['accuracy_promedio']:.4f}  (esperado: {caso_output['accuracy_promedio']:.4f})")
    print(f"  accuracy_por_fold : {np.round(resultado['accuracy_por_fold'], 4)}")
    print(f"  esperado por fold : {np.round(caso_output['accuracy_por_fold'], 4)}")
    coincide = np.allclose(resultado["accuracy_por_fold"], caso_output["accuracy_por_fold"])
    print(f"\n  ✓ Folds idénticos : {coincide}")
    print("═" * 55)

