# -*- coding: utf-8 -*-
"""answer-0418.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y2sagDrV4m6mY4dn8JyKRMcWlorrrLP_
"""

# ══════════════════════════════════════════════════════════════════════════════
# rankear_clientes_ventana_movil.py
# Ranking de clientes por suma móvil de montos en ventana deslizante
# ══════════════════════════════════════════════════════════════════════════════

import random
import numpy as np
import pandas as pd


# ── FUNCIÓN SOLUCIONADORA ────────────────────────────────────────────────────

def rankear_clientes_ventana_movil(
    df: pd.DataFrame,
    cliente_col: str,
    fecha_col: str,
    monto_col: str,
    ventana: int
) -> pd.DataFrame:
    """
    Para un DataFrame de movimientos de clientes, calcula qué cliente
    lidera la suma móvil de montos en cada fecha.

    Parámetros
    ----------
    df          : DataFrame con columnas de cliente, fecha y monto.
    cliente_col : Nombre de la columna de clientes.
    fecha_col   : Nombre de la columna de fechas (acepta texto o datetime).
    monto_col   : Nombre de la columna de montos.
    ventana     : Tamaño de la ventana para la suma móvil (rolling).

    Proceso
    -------
    1. Convierte fecha_col a datetime (errors='coerce').
    2. Elimina filas con fecha inválida o NaN en cliente_col / monto_col.
    3. Agrega por (cliente, fecha) sumando los montos del mismo día.
    4. Ordena por cliente y fecha.
    5. Calcula suma móvil de ventana=ventana por cliente (min_periods=1).
    6. Por cada fecha, selecciona el cliente con mayor suma móvil.
    7. En caso de empate, elige el de menor orden alfabético.

    Retorna
    -------
    pd.DataFrame con columnas [fecha_col, cliente_col, 'suma_movil'],
    ordenado por fecha_col ascendente e índice reiniciado.
    Si no quedan datos válidos, devuelve un DataFrame vacío con esas columnas.
    """
    # ── 1. Trabajar sobre copia para no modificar el original ────────────────
    trabajo = df.copy()
    trabajo[fecha_col] = pd.to_datetime(trabajo[fecha_col], errors="coerce")

    # ── 2. Limpiar filas inválidas ───────────────────────────────────────────
    trabajo = trabajo.dropna(subset=[cliente_col, fecha_col, monto_col])

    if trabajo.empty:
        return pd.DataFrame(columns=[fecha_col, cliente_col, "suma_movil"])

    # ── 3. Agregar: máximo una fila por (cliente, fecha) ────────────────────
    agregado = (
        trabajo
        .groupby([cliente_col, fecha_col], as_index=False)[monto_col]
        .sum()
        .sort_values([cliente_col, fecha_col])   # paso 4
        .reset_index(drop=True)
    )

    # ── 5. Suma móvil por cliente ────────────────────────────────────────────
    agregado["suma_movil"] = agregado.groupby(cliente_col)[monto_col].transform(
        lambda serie: serie.rolling(window=ventana, min_periods=1).sum()
    )

    # ── 6 & 7. Por cada fecha: cliente con mayor suma_movil (empate → alfabético)
    ranking = agregado.sort_values(
        [fecha_col, "suma_movil", cliente_col],
        ascending=[True, False, True],           # desc suma, asc cliente
    )

    top_por_fecha = (
        ranking
        .groupby(fecha_col, as_index=False)
        .first()[[fecha_col, cliente_col, "suma_movil"]]
        .sort_values(fecha_col)
        .reset_index(drop=True)
    )

    top_por_fecha["suma_movil"] = top_por_fecha["suma_movil"].astype(float)
    return top_por_fecha


# ── GENERADOR DE CASOS DE USO ────────────────────────────────────────────────

def generar_caso_de_uso_rankear_clientes_ventana_movil():
    cliente_col = "cliente"
    fecha_col   = "fecha"
    monto_col   = "monto"

    clientes    = [f"C{i:02d}" for i in range(1, random.randint(4, 7))]
    ventana     = random.randint(2, 5)
    base        = pd.Timestamp("2022-01-01") + pd.Timedelta(days=random.randint(0, 600))
    rango_dias  = random.randint(10, 24)
    n_filas     = random.randint(70, 150)

    filas = []
    for _ in range(n_filas):
        fecha   = ("no_fecha" if random.random() < 0.10
                   else (base + pd.Timedelta(days=random.randint(0, rango_dias - 1))
                         ).strftime("%Y-%m-%d"))
        cliente = None if random.random() < 0.07 else random.choice(clientes)
        monto   = (np.nan if random.random() < 0.10
                   else round(float(np.random.normal(loc=90.0, scale=40.0)), 2))
        filas.append({cliente_col: cliente, fecha_col: fecha, monto_col: monto})

    df = pd.DataFrame(filas)

    input_data  = {
        "df": df.copy(), "cliente_col": cliente_col,
        "fecha_col": fecha_col, "monto_col": monto_col, "ventana": ventana,
    }
    output_data = rankear_clientes_ventana_movil(
        df, cliente_col, fecha_col, monto_col, ventana
    )
    return input_data, output_data


# ── PRUEBAS ──────────────────────────────────────────────────────────────────

if __name__ == "__main__":

    # ── Test 1: caso de uso aleatorio ────────────────────────────────────────
    print("\n" + "═" * 65)
    print("  TEST 1 — CASO DE USO ALEATORIO")
    print("═" * 65)

    caso_input, caso_output = generar_caso_de_uso_rankear_clientes_ventana_movil()
    resultado = rankear_clientes_ventana_movil(**caso_input)

    print(f"  ventana        : {caso_input['ventana']}")
    print(f"  filas entrada  : {len(caso_input['df'])}")
    print(f"  filas resultado: {len(resultado)}")

    comp = caso_output.copy()
    comp = comp.rename(columns={
        caso_input['fecha_col']   : 'fecha',
        caso_input['cliente_col'] : 'esperado_cliente',
        'suma_movil'              : 'esperado_suma',
    })
    comp['obtenido_cliente'] = resultado[caso_input['cliente_col']].values
    comp['obtenido_suma']    = resultado['suma_movil'].values
    comp['ok_cliente']       = comp['esperado_cliente'] == comp['obtenido_cliente']
    comp['ok_suma']          = np.isclose(comp['esperado_suma'], comp['obtenido_suma'])

    print("\n  Primeras 10 fechas:")
    print(comp[['fecha','esperado_cliente','obtenido_cliente',
                'esperado_suma','obtenido_suma',
                'ok_cliente','ok_suma']].head(10).to_string(index=False))

    todo_ok = comp['ok_cliente'].all() and comp['ok_suma'].all()
    print(f"\n  ✓ Resultado idéntico al esperado: {todo_ok}")
    print("═" * 65)

print(resultado)