# -*- coding: utf-8 -*-
"""answer-0576.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E26HvJFBbNzYi8S5fWxNBmr4oTIlN0ar
"""

# ══════════════════════════════════════════════════════════════════════════════
# descomponer_serie_ventas.py
# Descomposición manual de series de tiempo: tendencia, estacionalidad, residuo
# ══════════════════════════════════════════════════════════════════════════════

import random
import numpy as np
import pandas as pd
from datetime import datetime, timedelta


# ── FUNCIÓN SOLUCIONADORA ────────────────────────────────────────────────────

def descomponer_serie_ventas(
    df: pd.DataFrame,
    fecha_col: str,
    valor_col: str,
    periodo: int
) -> tuple:
    """
    Descompone manualmente una serie de tiempo de ventas en:
    tendencia, estacionalidad y residuo.
    Evalúa si el residuo es aproximadamente normal (centrado en cero).

    Parámetros
    ----------
    df        : DataFrame con al menos las columnas fecha_col y valor_col.
    fecha_col : Nombre de la columna de fechas.
    valor_col : Nombre de la columna de valores numéricos (ventas).
    periodo   : Tamaño del periodo estacional (ej: 7 días, 12 meses).

    Proceso
    -------
    1. Convierte fecha_col a datetime y ordena ascendente.
    2. Tendencia = media móvil centrada (ventana=periodo), rellena bordes.
    3. Estacionalidad = media de (valor - tendencia) agrupada por (índice % periodo).
    4. Residuo = valor - tendencia - estacionalidad.
    5. Estadísticas del residuo: media, std, es_aprox_normal.

    Retorna
    -------
    Tupla (df_descompuesto, dict_stats):
        df_descompuesto : DataFrame original + columnas 'tendencia',
                          'estacionalidad', 'residuo'.
        dict_stats      : {'media_residuo', 'std_residuo', 'es_aprox_normal'}
    """
    # ── 1. Copia, convertir fecha, ordenar ───────────────────────────────────
    trabajo = df.copy()
    trabajo[fecha_col] = pd.to_datetime(trabajo[fecha_col])
    trabajo = trabajo.sort_values(fecha_col).reset_index(drop=True)

    # ── 2. Tendencia: media móvil centrada + relleno de bordes ───────────────
    trabajo["tendencia"] = (
        trabajo[valor_col]
        .rolling(window=periodo, center=True)
        .mean()
        .ffill()
        .bfill()
    )

    # ── 3. Estacionalidad ────────────────────────────────────────────────────
    sin_tendencia = trabajo[valor_col] - trabajo["tendencia"]
    posiciones    = np.arange(len(trabajo)) % periodo

    df_temp  = pd.DataFrame({"sin_tendencia": sin_tendencia, "posicion": posiciones})
    factores = df_temp.groupby("posicion")["sin_tendencia"].mean()  # factor por pos.

    trabajo["estacionalidad"] = pd.Series(posiciones).map(factores).values

    # ── 4. Residuo ───────────────────────────────────────────────────────────
    trabajo["residuo"] = (
        trabajo[valor_col] - trabajo["tendencia"] - trabajo["estacionalidad"]
    )

    # ── 5. Estadísticas del residuo ──────────────────────────────────────────
    residuos        = trabajo["residuo"].values
    media_residuo   = float(round(np.mean(residuos), 6))
    std_residuo     = float(round(np.std(residuos),  6))
    es_aprox_normal = bool(abs(media_residuo) < 0.05 * std_residuo)

    dict_stats = {
        "media_residuo"  : media_residuo,
        "std_residuo"    : std_residuo,
        "es_aprox_normal": es_aprox_normal,
    }

    return trabajo, dict_stats


# ── GENERADOR DE CASOS DE USO ────────────────────────────────────────────────

def generar_caso_de_uso_descomponer_serie_ventas():
    periodo    = random.choice([4, 6, 7, 12])
    n_periodos = random.randint(3, 6)
    n_filas    = periodo * n_periodos

    fecha_inicio = datetime(2022, 1, 1)
    fechas       = [fecha_inicio + timedelta(days=i) for i in range(n_filas)]

    tendencia_base       = np.linspace(100, 200, n_filas)
    factores_estacionales = np.tile(
        np.sin(np.linspace(0, 2 * np.pi, periodo)) * 20, n_periodos
    )
    ruido  = np.random.randn(n_filas) * 5
    ventas = tendencia_base + factores_estacionales + ruido

    df = pd.DataFrame({"fecha": fechas, "ventas": ventas})

    input_data = {
        "df": df.copy(), "fecha_col": "fecha",
        "valor_col": "ventas", "periodo": periodo
    }
    output_data = descomponer_serie_ventas(df, "fecha", "ventas", periodo)
    return input_data, output_data


# ── PRUEBAS ──────────────────────────────────────────────────────────────────

if __name__ == "__main__":

    # ── Test 1: caso de uso aleatorio ────────────────────────────────────────
    print("\n" + "═" * 65)
    print("  TEST 1 — CASO DE USO ALEATORIO")
    print("═" * 65)

    caso_input, (df_esp, stats_esp) = generar_caso_de_uso_descomponer_serie_ventas()
    df_res, stats_res = descomponer_serie_ventas(**caso_input)

    fc, vc, p = caso_input['fecha_col'], caso_input['valor_col'], caso_input['periodo']

    print(f"  periodo   : {p}  |  filas: {len(df_res)}")
    print(f"\n  Primeras 6 filas descompuestas:")
    cols = [fc, vc, 'tendencia', 'estacionalidad', 'residuo']
    print(df_res[cols].head(6).to_string(index=False, float_format="{:.4f}".format))

    print(f"\n  Estadísticas del residuo:")
    print(f"    media_residuo   obtenido={stats_res['media_residuo']:>12.6f}  "
          f"esperado={stats_esp['media_residuo']:>12.6f}  "
          f"ok={np.isclose(stats_res['media_residuo'], stats_esp['media_residuo'])}")
    print(f"    std_residuo     obtenido={stats_res['std_residuo']:>12.6f}  "
          f"esperado={stats_esp['std_residuo']:>12.6f}  "
          f"ok={np.isclose(stats_res['std_residuo'], stats_esp['std_residuo'])}")
    print(f"    es_aprox_normal obtenido={str(stats_res['es_aprox_normal']):>12}  "
          f"esperado={str(stats_esp['es_aprox_normal']):>12}  "
          f"ok={stats_res['es_aprox_normal'] == stats_esp['es_aprox_normal']}")

    df_ok    = np.allclose(df_res['residuo'].values, df_esp['residuo'].values)
    stats_ok = (np.isclose(stats_res['media_residuo'], stats_esp['media_residuo']) and
                np.isclose(stats_res['std_residuo'],   stats_esp['std_residuo']) and
                stats_res['es_aprox_normal'] == stats_esp['es_aprox_normal'])
    print(f"\n  ✓ DataFrame idéntico : {df_ok}")
    print(f"  ✓ Stats idénticas    : {stats_ok}")
    print("═" * 65)